//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.07 at 08:07:13 PM CEST 
//


package com.xml.publications.model.ScientificPublication;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.publications.model.ScientificPublication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.publications.model.ScientificPublication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScientificPublication }
     * 
     */
    public ScientificPublication createScientificPublication() {
        return new ScientificPublication();
    }

    /**
     * Create an instance of {@link ScientificPublication.Chapter }
     * 
     */
    public ScientificPublication.Chapter createScientificPublicationChapter() {
        return new ScientificPublication.Chapter();
    }

    /**
     * Create an instance of {@link ScientificPublication.Chapter.Paragraph }
     * 
     */
    public ScientificPublication.Chapter.Paragraph createScientificPublicationChapterParagraph() {
        return new ScientificPublication.Chapter.Paragraph();
    }

    /**
     * Create an instance of {@link ScientificPublication.Metadata }
     * 
     */
    public ScientificPublication.Metadata createScientificPublicationMetadata() {
        return new ScientificPublication.Metadata();
    }

    /**
     * Create an instance of {@link ScientificPublication.Reference }
     * 
     */
    public ScientificPublication.Reference createScientificPublicationReference() {
        return new ScientificPublication.Reference();
    }

    /**
     * Create an instance of {@link ScientificPublication.Chapter.Paragraph.Citation }
     * 
     */
    public ScientificPublication.Chapter.Paragraph.Citation createScientificPublicationChapterParagraphCitation() {
        return new ScientificPublication.Chapter.Paragraph.Citation();
    }

    /**
     * Create an instance of {@link ScientificPublication.Metadata.Authors }
     * 
     */
    public ScientificPublication.Metadata.Authors createScientificPublicationMetadataAuthors() {
        return new ScientificPublication.Metadata.Authors();
    }

    /**
     * Create an instance of {@link ScientificPublication.Metadata.Reviewers }
     * 
     */
    public ScientificPublication.Metadata.Reviewers createScientificPublicationMetadataReviewers() {
        return new ScientificPublication.Metadata.Reviewers();
    }

}
