//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.07 at 08:08:36 PM CEST 
//


package com.xml.publications.model.Review;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="criteriaEvaluation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="relevanceOfResearchProblem" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
 *                   &lt;element name="conceptualQuality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
 *                   &lt;element name="methodologicalQuality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
 *                   &lt;element name="readability" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
 *                   &lt;element name="originality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="overallEvaluation">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="acceptable without revisions"/>
 *               &lt;enumeration value="acceptable with minor revisions"/>
 *               &lt;enumeration value="acceptable with major revisions"/>
 *               &lt;enumeration value="reject"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="commentToAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="commentsToEditor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reviewId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="submissionDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="publicationId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reviewedBy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "criteriaEvaluation",
    "overallEvaluation",
    "commentToAuthor",
    "commentsToEditor"
})
@XmlRootElement(name = "review")
public class Review {

    @XmlElement(required = true)
    protected Review.CriteriaEvaluation criteriaEvaluation;
    @XmlElement(required = true)
    protected String overallEvaluation;
    @XmlElement(required = true)
    protected String commentToAuthor;
    @XmlElement(required = true)
    protected String commentsToEditor;
    @XmlAttribute(name = "reviewId")
    protected String reviewId;
    @XmlAttribute(name = "submissionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar submissionDate;
    @XmlAttribute(name = "publicationId")
    protected String publicationId;
    @XmlAttribute(name = "reviewedBy")
    protected String reviewedBy;

    /**
     * Gets the value of the criteriaEvaluation property.
     * 
     * @return
     *     possible object is
     *     {@link Review.CriteriaEvaluation }
     *     
     */
    public Review.CriteriaEvaluation getCriteriaEvaluation() {
        return criteriaEvaluation;
    }

    /**
     * Sets the value of the criteriaEvaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.CriteriaEvaluation }
     *     
     */
    public void setCriteriaEvaluation(Review.CriteriaEvaluation value) {
        this.criteriaEvaluation = value;
    }

    /**
     * Gets the value of the overallEvaluation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverallEvaluation() {
        return overallEvaluation;
    }

    /**
     * Sets the value of the overallEvaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverallEvaluation(String value) {
        this.overallEvaluation = value;
    }

    /**
     * Gets the value of the commentToAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentToAuthor() {
        return commentToAuthor;
    }

    /**
     * Sets the value of the commentToAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentToAuthor(String value) {
        this.commentToAuthor = value;
    }

    /**
     * Gets the value of the commentsToEditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentsToEditor() {
        return commentsToEditor;
    }

    /**
     * Sets the value of the commentsToEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentsToEditor(String value) {
        this.commentsToEditor = value;
    }

    /**
     * Gets the value of the reviewId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewId() {
        return reviewId;
    }

    /**
     * Sets the value of the reviewId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewId(String value) {
        this.reviewId = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionDate(XMLGregorianCalendar value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the publicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationId() {
        return publicationId;
    }

    /**
     * Sets the value of the publicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationId(String value) {
        this.publicationId = value;
    }

    /**
     * Gets the value of the reviewedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewedBy() {
        return reviewedBy;
    }

    /**
     * Sets the value of the reviewedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewedBy(String value) {
        this.reviewedBy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="relevanceOfResearchProblem" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
     *         &lt;element name="conceptualQuality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
     *         &lt;element name="methodologicalQuality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
     *         &lt;element name="readability" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
     *         &lt;element name="originality" type="{http://www.ftn.uns.ac.rs/XML/Review}TCriteriaGrade"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relevanceOfResearchProblem",
        "conceptualQuality",
        "methodologicalQuality",
        "readability",
        "originality"
    })
    public static class CriteriaEvaluation {

        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TCriteriaGrade relevanceOfResearchProblem;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TCriteriaGrade conceptualQuality;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TCriteriaGrade methodologicalQuality;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TCriteriaGrade readability;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected TCriteriaGrade originality;

        /**
         * Gets the value of the relevanceOfResearchProblem property.
         * 
         * @return
         *     possible object is
         *     {@link TCriteriaGrade }
         *     
         */
        public TCriteriaGrade getRelevanceOfResearchProblem() {
            return relevanceOfResearchProblem;
        }

        /**
         * Sets the value of the relevanceOfResearchProblem property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCriteriaGrade }
         *     
         */
        public void setRelevanceOfResearchProblem(TCriteriaGrade value) {
            this.relevanceOfResearchProblem = value;
        }

        /**
         * Gets the value of the conceptualQuality property.
         * 
         * @return
         *     possible object is
         *     {@link TCriteriaGrade }
         *     
         */
        public TCriteriaGrade getConceptualQuality() {
            return conceptualQuality;
        }

        /**
         * Sets the value of the conceptualQuality property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCriteriaGrade }
         *     
         */
        public void setConceptualQuality(TCriteriaGrade value) {
            this.conceptualQuality = value;
        }

        /**
         * Gets the value of the methodologicalQuality property.
         * 
         * @return
         *     possible object is
         *     {@link TCriteriaGrade }
         *     
         */
        public TCriteriaGrade getMethodologicalQuality() {
            return methodologicalQuality;
        }

        /**
         * Sets the value of the methodologicalQuality property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCriteriaGrade }
         *     
         */
        public void setMethodologicalQuality(TCriteriaGrade value) {
            this.methodologicalQuality = value;
        }

        /**
         * Gets the value of the readability property.
         * 
         * @return
         *     possible object is
         *     {@link TCriteriaGrade }
         *     
         */
        public TCriteriaGrade getReadability() {
            return readability;
        }

        /**
         * Sets the value of the readability property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCriteriaGrade }
         *     
         */
        public void setReadability(TCriteriaGrade value) {
            this.readability = value;
        }

        /**
         * Gets the value of the originality property.
         * 
         * @return
         *     possible object is
         *     {@link TCriteriaGrade }
         *     
         */
        public TCriteriaGrade getOriginality() {
            return originality;
        }

        /**
         * Sets the value of the originality property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCriteriaGrade }
         *     
         */
        public void setOriginality(TCriteriaGrade value) {
            this.originality = value;
        }

    }

}
